"""Cuckoo 2 REST API adapter; analysis is performed by the external VM sandbox."""
import json
import secrets
import time
from urllib.error import HTTPError, URLError
from urllib.parse import urlsplit
from urllib.request import Request, build_opener, HTTPRedirectHandler, ProxyHandler
from .analyzer import MAX_TARGETS


class NoRedirect(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


class SandboxError(Exception):
    pass


class Cuckoo:
    def __init__(self, base_url, token="", request_timeout=15):
        parsed = urlsplit(base_url)
        if parsed.scheme not in {"http", "https"} or not parsed.hostname or parsed.username or parsed.password or parsed.query or parsed.fragment:
            raise ValueError("Sandbox URL'si http(s) adresi olmalı; kullanıcı bilgisi/query içeremez.")
        if parsed.scheme == "http" and parsed.hostname not in {"127.0.0.1", "localhost", "::1"}:
            raise ValueError("Uzak sandbox için HTTPS kullanın.")
        self.base = base_url.rstrip("/")
        self.token = token
        self.timeout = request_timeout
        # Ignore ambient proxies; do not forward the API token through redirects.
        self.opener = build_opener(ProxyHandler({}), NoRedirect())

    def request(self, path, data=None, content_type=None):
        headers = {"Accept": "application/json"}
        if self.token:
            headers["Authorization"] = "Bearer " + self.token
        if content_type:
            headers["Content-Type"] = content_type
        req = Request(self.base + path, data=data, headers=headers)
        try:
            with self.opener.open(req, timeout=self.timeout) as response:
                raw = response.read(10 * 1024 * 1024 + 1)
                if len(raw) > 10 * 1024 * 1024:
                    raise SandboxError("Sandbox yanıtı boyut sınırını aştı.")
                return json.loads(raw)
        except HTTPError as exc:
            raise SandboxError(f"Sandbox HTTP {exc.code}; uç nokta ve erişimi kontrol edin.") from None
        except (URLError, TimeoutError, OSError, ValueError) as exc:
            raise SandboxError("Sandbox bağlantısı/JSON yanıtı başarısız.") from None

    def submit(self, target):
        boundary = "mailguard" + secrets.token_hex(16)
        if target["kind"] == "file":
            # Name generated by analyzer, not the untrusted mail filename.
            name = target["name"]
            prefix = f'--{boundary}\r\nContent-Disposition: form-data; name="file"; filename="{name}"\r\nContent-Type: application/octet-stream\r\n\r\n'.encode()
            data = prefix + target["data"] + f"\r\n--{boundary}--\r\n".encode()
        else:
            data = (f'--{boundary}\r\nContent-Disposition: form-data; name="url"\r\n\r\n{target["url"]}\r\n--{boundary}--\r\n').encode()
        result = self.request("/tasks/create/" + target["kind"], data, "multipart/form-data; boundary=" + boundary)
        task_id = result.get("task_id") if isinstance(result, dict) else None
        if type(task_id) is not int or task_id <= 0:
            raise SandboxError("Cuckoo task_id alınamadı; desteklenen API sürümünü kontrol edin.")
        return task_id

    def run(self, targets, wait_seconds=120):
        tasks = []
        for target in targets[:MAX_TARGETS]:
            label = target.get("sha256") or target.get("url")
            item = {"kind": target["kind"], "target": label}
            tasks.append(item)
            try:
                item.update(task_id=self.submit(target), status="submitted")
            except SandboxError as exc:
                item.update(status="error", error=str(exc))
        deadline = time.monotonic() + wait_seconds
        pending = [x for x in tasks if x["status"] == "submitted"]
        while pending and time.monotonic() < deadline:
            for item in pending[:]:
                try:
                    state = self.request(f'/tasks/view/{item["task_id"]}')
                    status = state.get("task", {}).get("status", "unknown")
                    if status == "reported":
                        result = self.request(f'/tasks/report/{item["task_id"]}/json')
                        item.update(status="reported", result=result)
                        pending.remove(item)
                    elif status.startswith("failed"):
                        item.update(status=status)
                        pending.remove(item)
                    else:
                        item["remote_status"] = status
                except (SandboxError, AttributeError) as exc:
                    item.update(status="error", error="Sandbox durum/rapor sorgusu başarısız.")
                    pending.remove(item)
            if pending:
                time.sleep(min(2, max(0, deadline - time.monotonic())))
        for item in pending:
            item["status"] = "pending"  # Never report a timed-out task as clean.
        return {"status": "finished" if tasks and all(x["status"] == "reported" for x in tasks) else "incomplete" if tasks else "no_targets",
                "tasks": tasks, "skipped_targets": max(0, len(targets) - MAX_TARGETS)}
